name: IaC Deploy Workflow

on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Ensure backend S3 bucket exists or create it
        run: ../lambda/init_state_bucket.sh

      - name: Terraform Init
        run: terraform init 

      - name: Terraform Plan and Optional Lambda Invoke
        run: |
          terraform plan -detailed-exitcode
          code=$?
          if [ "$code" -eq 0 ]; then
            echo "No infrastructure changes. Invoking Lambda"
            ../lambda/lambda_test.sh
          elif [ "$code" -eq 2 ]; then
            echo "Changes detected. Lambda will be invoked via Terraform Apply."
        
          fi
          
      - name: Terraform Apply
        run: terraform apply -auto-approve 
