name : IaC Deploy Workflow

on : 
    workflow_dispatch:
        
jobs :
    Deploy:
        runs-on: ubuntu-latest

        steps : 

            - name: Checkout Repository
              uses: actions/checkout@v3


            - name : Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                    terraform_version: "1.1.7"
            
            
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4.1.0
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-central-1

            - name: Terraform Init
              run : terraform init

            - name: Import existing AWS resources
              run: |
              terraform import aws_s3_bucket.assign_bucket assignement-bucket-fadi7 || true
              terraform import aws_iam_policy.lambda_s3_policy arn:aws:iam::992824239500:policy/lambda_s3_policy || true
              terraform import aws_iam_role.assign_iam assign_iam || true
              terraform import aws_iam_role_policy_attachment.test_attach assign_iam/arn:aws:iam::992824239500:policy/lambda_s3_policy || true
              terraform import aws_lambda_function.s3_lambda list-s3-files || true
              terraform import aws_lambda_permission.allow_s3 list-s3-files/AllowExecutionFromS3 || true
              terraform import aws_sns_topic.assign_topic arn:aws:sns:eu-central-1:992824239500:user-notifications || true

            - name: Terraform Apply
              run: terraform apply -auto-approve                